### ISSUE TITLE
Having this package installed breaks bracket auto-completion in HTML files

### ISSUE THREAD

**Issue by HopefulLlama** [somebee/sublime-imba#1]
Typing '</' in a HTML file will cause Sublime to auto-complete and close the tag. I.e: in the case of a `<div>` you will get `</div>`.

With Imba installed you instead get '</div>>'. This is extremely annoying as closing a tag then means you must manually delete a closing bracket.

**Comment by somebee** [comment]
Will look into it now. Thanks for reporting.

**Comment by HopefulLlama** [comment]
I think the source of this issue is that Sublime by default does not close a bracket on typing, whereas Imba will.

So it seems that typing `<` gives `<>`, then the next keystroke of `/` gives `</>` which prompts Sublime to add in `div>` to close up the tag auto-magically. Due to Imba's eagerness to close the bracket already, we get `</div>>`.

**Comment by somebee** [comment]
Should be fixed now. The plugin should autoupdate if you installed it through Package Control. Could take an hour or two though (Package Control does not check for updates more than once an hour or so).
