### ISSUE TITLE
Comment toggle not working

### ISSUE THREAD

**Issue by IstoraMandiri** [somebee/sublime-imba#2]
Hi, I don't seem to be able to use one of my favourite shortcuts: toggle comment `Command + /`\- also doesn't work if I select it from the context menu or search box.

Is there some config step I'm missing?

Cheers

**Comment by lukeed** [comment]
I was just coming to request this as well... probably the most common shortcut.

You're not missing any configs @hitchcott. It's just not in the plugin definition

**Comment by lukeed** [comment]
@somebee thanks for this! Doesn't look like Sublime knows there's an update though.

**Comment by somebee** [comment]
@lukeed Correct. I considered including a few more fixes, but why wait. I'll tag and push it now :) Usually takes a few hours before it is reflected in package manager I think.

**Comment by lukeed** [comment]
Great :) I'm about to do a lot of Imba work today, was getting tired of manually typing comments :stuck_out_tongue_winking_eye:
